#!/bin/sh
# scripts/regen-dist.sh — Regenerate dist/sigil.cyr by concatenating the
# `[lib].modules` list from cyrius.cyml. The dist bundle is sigil's
# consumer-facing single-file artifact; cyrius's old `cyrius distlib`
# subcommand that originally generated it has been retired, so this
# script takes over.
#
# When to run:
#   - Any time `cyrius.cyml [lib].modules` changes.
#   - Any time a module in the list gets a load-bearing edit that
#     downstream dist consumers need to see (new public API,
#     CVE-style fix, etc.). For non-dist consumers (sibling-checkout
#     callers that use `src/lib.cyr` directly), running this script
#     isn't required — they'll see the updated source automatically.
#
# Dist contract: the bundle MUST be self-contained. The four
# agnosys-wrapping modules are deliberately excluded from the
# `[lib].modules` list (per cyrius.cyml header comment) — consumers
# that need them include via `src/lib.cyr` against a sibling
# agnosys checkout.

set -e
cd "$(dirname "$0")/.."

# Module order — keep in sync with cyrius.cyml [lib].modules.
# Order matches src/lib.cyr's include order so dependent modules
# follow their dependencies.
MODULES="
src/types.cyr
src/error.cyr
src/crypto_scratch.cyr
src/sha_ni.cyr
src/sha256.cyr
src/hex.cyr
src/hmac.cyr
src/hkdf.cyr
src/aes_ni.cyr
src/aes_gcm.cyr
src/poly1305.cyr
src/chacha20.cyr
src/chacha20poly1305.cyr
src/sha512.cyr
src/sha384.cyr
src/hmac_sha384.cyr
src/hkdf_sha384.cyr
src/tls12_prf.cyr
src/bigint_ext.cyr
src/ed25519.cyr
src/x25519.cyr
src/ecdsa_p256.cyr
src/ecdsa_p384.cyr
src/ecdsa_sign.cyr
src/x509.cyr
src/pem.cyr
src/privkey.cyr
src/sgx.cyr
src/sev_snp.cyr
src/tdx.cyr
src/seal.cyr
src/mldsa_params.cyr
src/mldsa_reduce.cyr
src/mldsa_ntt.cyr
src/mldsa_poly.cyr
src/mldsa_rounding.cyr
src/mldsa_encode.cyr
src/mldsa_sample.cyr
src/mldsa.cyr
src/trust.cyr
src/integrity.cyr
src/policy.cyr
src/audit.cyr
src/verify.cyr
"

VERSION=$(cat VERSION)
OUT=dist/sigil.cyr

{
  echo "# sigil.cyr -- bundled distribution"
  echo "# Version: $VERSION"
  echo "# Generated by: scripts/regen-dist.sh"
  echo "# Do not edit -- rebuild via the regen script when [lib].modules changes."
  echo ""
  for m in $MODULES; do
    base=$(basename "$m")
    echo ""
    echo "# --- $base ---"
    echo ""
    cat "$m"
  done
} > "$OUT"

echo "wrote $OUT ($(wc -l < $OUT) lines, $(wc -c < $OUT) bytes)"
