#!/bin/sh
# scripts/regen-dist.sh — Regenerate dist/sigil.cyr by concatenating the
# `[lib].modules` list from cyrius.cyml. The dist bundle is sigil's
# consumer-facing single-file artifact; cyrius's old `cyrius distlib`
# subcommand that originally generated it has been retired, so this
# script takes over.
#
# When to run:
#   - Any time `cyrius.cyml [lib].modules` changes.
#   - Any time a module in the list gets a load-bearing edit that
#     downstream dist consumers need to see (new public API,
#     CVE-style fix, etc.). For non-dist consumers (sibling-checkout
#     callers that use `src/lib.cyr` directly), running this script
#     isn't required — they'll see the updated source automatically.
#
# Dist contract: the bundle MUST be self-contained. As of 3.8.1 the
# trust stack is internalized and as of 3.9.0 fully bundled (P2 — trust
# API first-class in dist): the support modules (sys_error/sys_util/
# sysinfo) + cores (*_core, dmverity, luks) + wrappers (tpm/ima/
# secureboot/certpin) are all in the list below. No external agnosys
# dep remains. (Per cyrius.cyml header comment.)

set -e
cd "$(dirname "$0")/.."

# Module order — keep in sync with cyrius.cyml [lib].modules.
# Order matches src/lib.cyr's include order so dependent modules
# follow their dependencies.
MODULES="
src/sys_error.cyr
src/sys_util.cyr
src/sysinfo.cyr
src/certpin_core.cyr
src/tpm_core.cyr
src/ima_core.cyr
src/secureboot_core.cyr
src/dmverity.cyr
src/luks.cyr
src/types.cyr
src/error.cyr
src/random.cyr
src/crypto_scratch.cyr
src/sha_ni.cyr
src/sha256.cyr
src/hex.cyr
src/hmac.cyr
src/hkdf.cyr
src/aes_ni.cyr
src/aes_gcm.cyr
src/poly1305.cyr
src/chacha20.cyr
src/chacha20poly1305.cyr
src/sha512.cyr
src/sha384.cyr
src/hmac_sha384.cyr
src/hkdf_sha384.cyr
src/tls12_prf.cyr
src/bigint_ext.cyr
src/bignum.cyr
src/ed25519.cyr
src/x25519.cyr
src/ecdsa_p256.cyr
src/ecdsa_p384.cyr
src/ecdsa_sign.cyr
src/x509.cyr
src/pem.cyr
src/privkey.cyr
src/rsa.cyr
src/sgx.cyr
src/sev_snp.cyr
src/tdx.cyr
src/seal.cyr
src/mldsa_params.cyr
src/mldsa_reduce.cyr
src/mldsa_ntt.cyr
src/mldsa_poly.cyr
src/mldsa_rounding.cyr
src/mldsa_encode.cyr
src/mldsa_sample.cyr
src/mldsa.cyr
src/trust.cyr
src/integrity.cyr
src/policy.cyr
src/audit.cyr
src/tpm.cyr
src/ima.cyr
src/secureboot.cyr
src/certpin.cyr
src/verify.cyr
"

VERSION=$(cat VERSION)
OUT=dist/sigil.cyr

{
  echo "# sigil.cyr -- bundled distribution"
  echo "# Version: $VERSION"
  echo "# Generated by: scripts/regen-dist.sh"
  echo "# Do not edit -- rebuild via the regen script when [lib].modules changes."
  echo ""
  for m in $MODULES; do
    base=$(basename "$m")
    echo ""
    echo "# --- $base ---"
    echo ""
    # The bundle concatenates every MODULES entry exactly once, so a module's
    # own `include "src/*.cyr"` directives (e.g. sha256.cyr pulling sha_ni.cyr,
    # aes_gcm.cyr pulling aes_ni.cyr — needed for the sibling-checkout path)
    # are REDUNDANT here. Left in, they ship as un-inlined includes that a
    # strict-include consumer (cyrius >= 6.1.35) hard-errors on (the file is
    # absent in the fold). Strip them so the bundle is genuinely self-contained;
    # the `#ifndef`-guards around them stay as harmless empty conditionals, and
    # still do their job on the sibling-checkout path. See cyrius CHANGELOG
    # [6.1.36] — this replaces the per-include `#ifndef` paper-over.
    sed '/^[[:space:]]*include "src\/[^"]*\.cyr"/d' "$m"
  done
} > "$OUT"

# Self-contained invariant: the bundle MUST NOT reference any src/ path (those
# files do not exist at the consumer). Fail loudly if an un-inlined include
# slipped through — that is exactly the distlib bug the strip above fixes.
if grep -nE '^[[:space:]]*include "src/' "$OUT" >/dev/null 2>&1; then
  echo "ERROR: $OUT still contains un-inlined src/ includes (distlib self-containment violated):" >&2
  grep -nE '^[[:space:]]*include "src/' "$OUT" >&2
  rm -f "$OUT"
  exit 1
fi

echo "wrote $OUT ($(wc -l < $OUT) lines, $(wc -c < $OUT) bytes)"
